#global:
#  resolve_timeout: 5m
#  smtp_smarthost: 'smtp.mxhichina.com:25'
#  smtp_from: 'kaifen.xie@cloudtogo.cn'
#  smtp_auth_username: 'kaifen.xie@cloudtogo.cn'
#  smtp_auth_password: '219112114xkfXKF'
#  smtp_hello: 'cloudtogo.cn'
#  smtp_require_tls: true
route:
  group_by: ['job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: webhook
  routes:
    - receiver: webhook
      match:
        alertname: CoreDNSDown
receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://10.10.13.30:8046/hooks/alertmanager'
        send_resolved: false
